on:
  push:
    branches: [main]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  build_site:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site()
        shell: Rscript {0}

  deploy_site:
    name: Deploy to Wave Dev 🚀
    uses: StudioBandLLC/github-actions/.github/workflows/deploy-shiny.yml@v1
    needs: build_site
    with:
      target_env: prod
      source_path: "~/Projects/${{ github.event.repository.name }}/docs/*"
      remote_path: "/mnt/wave/shiny-server/_data/${{ github.event.repository.name }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      private_ssh_key: ${{ secrets.INFISICAL_SSH_PRIVATE_KEY_PROD }}
      ssh_host: ${{ secrets.INFISICAL_SSH_HOST_PROD }}
      ssh_username: ${{ secrets.INFISICAL_SSH_USERNAME_PROD }}
