name: ToDo to Issue
run-name: convert ToDo comments in code to GitHub Issues

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      issues: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "Convert TODOs to Issues"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOSE_ISSUES: true  # Automatically close issue when removed

